spring:
  application:
    name: discodeit
  boot:
    admin:
      client:
        instance:
          name: discodeit
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0
  datasource:
    url: ${spring.datasource.url:unknown}
    driver-class-name: ${spring.datasource.driver-class-name:unknown}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto:unknown}
  storage:
    type: ${discodeit.storage.type:unknown}
    path: ${discodeit.storage.local.root-path:unknown}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size:unknown}
    max-request-size: ${spring.servlet.multipart.max-request-size:unknown}