spring:
  application:
    name: discodeit
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

logging:
  level:
    root: INFO